-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.5
    -   id: end-of-file-fixer
        language_version: python3.5
        exclude: ^\.activate\.sh$
    -   id: autopep8-wrapper
        language_version: python3.5
    -   id: check-docstring-first
        language_version: python3.5
    -   id: check-merge-conflict
        language_version: python3.5
    -   id: check-yaml
        language_version: python3.5
    -   id: debug-statements
        language_version: python3.5
    -   id: double-quote-string-fixer
        language_version: python3.5
    -   id: name-tests-test
        language_version: python3.5
    -   id: flake8
        language_version: python3.5
    -   id: check-added-large-files
        language_version: python3.5
        exclude: ^\.activate\.sh$
    -   id: check-byte-order-marker
        language_version: python3.5
    -   id: fix-encoding-pragma
        language_version: python3.5
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3.5
        args: [
            '--add-import', 'from __future__ import absolute_import',
            '--add-import', 'from __future__ import unicode_literals',
        ]
