language: python
python:
    - '3.6'
dist: trusty
sudo: false
install: pip install tox coveralls
script: make test
after_success:
    - coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.pre-commit
